### ISSUE TITLE
如何发布到hexo博客

### ISSUE THREAD

**Issue by sikenali** [cyy0418/ceditor#2]
![_ceditor_20180205133956](https://user-images.githubusercontent.com/26103116/35789856-1d30dd0c-0a7a-11e8-8fd5-84021698128e.png)

我下载appimage安装了也正常登录了，但是发布就转圈了下，个人设置里面说安装nodejs和git 这2个也安装了。

**Comment by cyyjs** [comment]
可直接通过在`shell`执行 `which node`或`which git`命令来检查命令是否可用

**Comment by sikenali** [comment]
~  which node
/usr/bin/node
 ~  which git
/usr/bin/git
